//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocsManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AgreementDocument : Documents
    {
        [Required]
        [Display(Name = "Вид Договора")]
        public string TypeAgreement { get; set; }
        [Required]
        [Display(Name = "срок Договора")]
        public System.DateTime DeadlineAgreement { get; set; }
        [Required]
        [Display(Name = "Введите, назвоние контрагента")]
        public string Contractor { get; set; }
        [Required]
        [Range(0.01, double.MaxValue,
            ErrorMessage = "Введите, Положительную Цену")]
        public decimal Amount { get; set; }
    }
}
