//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocsManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentsdbContext : DbContext
    {
        public DocumentsdbContext()
            : base("name=DocumentsdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgreementDocument> AgreementDocuments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<ServiceDocument> ServiceDocuments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
